jobs:
  main:
    name: Check
    runs-on: ubuntu-20.04

    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Fetch Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./test/test

name: Main

on:
  schedule:
    - cron: "5 1/3 * * *"
